#pragma once

#include "Object.h"

DEFINE_TYPE_ID(Object, 1)
DEFINE_TYPE_ID(ScriptObject, 2)
DEFINE_TYPE_ID(Component, 3)
DEFINE_TYPE_ID(Texture2D, 4)
DEFINE_TYPE_ID(Camera, 5)
DEFINE_TYPE_ID(Resource, 6)
DEFINE_TYPE_ID(TextureResource, 7)
DEFINE_TYPE_ID(ImageResource, 8)
DEFINE_TYPE_ID(AudioResource, 9)
DEFINE_TYPE_ID(Transform, 10)
DEFINE_TYPE_ID(RenderPass, 11)
DEFINE_TYPE_ID(TextureCube, 12)
DEFINE_TYPE_ID(Shader, 13)
DEFINE_TYPE_ID(Light, 14)
DEFINE_TYPE_ID(Material, 15)
DEFINE_TYPE_ID(RenderOrder, 16)
DEFINE_TYPE_ID(GameObject, 17)
DEFINE_TYPE_ID(AsyncCommand, 18)
DEFINE_TYPE_ID(BinaryBuffer, 19)
DEFINE_TYPE_ID(Socket, 20)
DEFINE_TYPE_ID(HttpCurl, 21)
DEFINE_TYPE_ID(WWW, 22)